[package]
name = "json_value_description"
version = "0.1.0"
authors = ["Craig Hills <chills@gmail.com>"]
edition = "2018"

[dependencies]
serde = "^1.0.0"
serde_derive = "^1.0.0"
serde_json = "^1.0.0"

